//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComponenteTef {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComponenteTef.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não autorizado. Por favor, realize a autenticação para utilizar o CapptaGpPlus.
        /// </summary>
        internal static string RESULTADO_CAPPTA_1 {
            get {
                return ResourceManager.GetString("RESULTADO_CAPPTA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma reimpressão ou cancelamento foi executada dentro de uma sessão multi-cartões.
        /// </summary>
        internal static string RESULTADO_CAPPTA_10 {
            get {
                return ResourceManager.GetString("RESULTADO_CAPPTA_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CapptaGpPlus esta sendo inicializado, tente novamente em alguns instantes.
        /// </summary>
        internal static string RESULTADO_CAPPTA_2 {
            get {
                return ResourceManager.GetString("RESULTADO_CAPPTA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da requisição recebida pelo CapptaGpPlus é inválido.
        /// </summary>
        internal static string RESULTADO_CAPPTA_3 {
            get {
                return ResourceManager.GetString("RESULTADO_CAPPTA_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação cancelada pelo operador.
        /// </summary>
        internal static string RESULTADO_CAPPTA_4 {
            get {
                return ResourceManager.GetString("RESULTADO_CAPPTA_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento não autorizado/pendente/não encontrado.
        /// </summary>
        internal static string RESULTADO_CAPPTA_5 {
            get {
                return ResourceManager.GetString("RESULTADO_CAPPTA_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento ou cancelamento negados pela rede adquirente.
        /// </summary>
        internal static string RESULTADO_CAPPTA_6 {
            get {
                return ResourceManager.GetString("RESULTADO_CAPPTA_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro interno no CapptaGpPlus.
        /// </summary>
        internal static string RESULTADO_CAPPTA_7 {
            get {
                return ResourceManager.GetString("RESULTADO_CAPPTA_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro na comunicação entre a CappAPI e o CapptaGpPlus.
        /// </summary>
        internal static string RESULTADO_CAPPTA_8 {
            get {
                return ResourceManager.GetString("RESULTADO_CAPPTA_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível realizar uma operação sem que se tenha finalizado o último pagamento.
        /// </summary>
        internal static string RESULTADO_CAPPTA_9 {
            get {
                return ResourceManager.GetString("RESULTADO_CAPPTA_9", resourceCulture);
            }
        }
    }
}
